<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYR7taJu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYR7taJu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYR7taJu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYR7taJu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYR7taJu\App_KernelDevDebugContainer([
    'container.build_hash' => 'YR7taJu',
    'container.build_id' => 'c1850f27',
    'container.build_time' => 1774565880,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYR7taJu');
